version: 2.1

orbs:
  gor: hubci/goreleaser@1.0
  osd: circleci/os-detect@0.3.0

workflows:
  main:
    jobs:
      - test
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: "0.149.0"
          go-version: "1.15.6"
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          context: main

jobs:
  test:
    docker:
      - image: cimg/go:1.15.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1
      - run:
          name: "Download Dependancies"
          command: cd pmm && go mod download
      - run:
          name: "Run Tests"
          command: cd pmm && go test ./...
      - save_cache:
          key: go-mod-v1
          paths:
            - "/go/pkg/mod"
